# fly.toml app configuration file generated for bowlpool on 2023-12-29T11:05:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bowlpool"
primary_region = "sea"
console_command = "/code/manage.py shell"

[build]

[env]
PORT = "8000"
BOWLPOOL_DB_PATH = "/code/bowlpool.sqlite3"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[[statics]]
guest_path = "/code/static"
url_prefix = "/static/"
