# Generated by Django 4.2.7 on 2023-11-29 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BowlGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BowlMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowl_year', models.IntegerField(db_index=True, help_text='Year of the matchup if before January 1, otherwise the year before')),
                ('start_time', models.DateTimeField(help_text='Stored as UTC')),
                ('home_team_point_spread', models.IntegerField(help_text="Home team's point spread - negative means the home team is favored, positive means the away team is favored")),
                ('away_team_final_score', models.IntegerField(blank=True, null=True)),
                ('home_team_final_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BowlMatchupPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.IntegerField()),
                ('bowl_matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowlpool_app.bowlmatchup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowlpool_app.team')),
            ],
        ),
        migrations.AddField(
            model_name='bowlmatchup',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='bowlpool_app.team'),
        ),
        migrations.AddField(
            model_name='bowlmatchup',
            name='bowl_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowlpool_app.bowlgame'),
        ),
        migrations.AddField(
            model_name='bowlmatchup',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='bowlpool_app.team'),
        ),
        migrations.AddConstraint(
            model_name='bowlmatchuppick',
            constraint=models.UniqueConstraint(fields=('user', 'bowl_matchup'), name='unique_matchups_for_user'),
        ),
        migrations.AddConstraint(
            model_name='bowlmatchup',
            constraint=models.UniqueConstraint(fields=('bowl_year', 'bowl_game'), name='unique_bowls_for_year'),
        ),
    ]
