# Generated by Django 4.2.7 on 2023-12-02 20:12

import bowlpool_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlpool_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', bowlpool_app.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='bowlgame',
            name='cfp_playoff_game',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
