# Generated by Django 4.2.7 on 2023-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlpool_app', '0002_alter_user_managers_bowlgame_cfp_playoff_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowlgame',
            name='cfp_playoff_game',
        ),
        migrations.AddField(
            model_name='bowlmatchup',
            name='cfp_playoff_game',
            field=models.BooleanField(default=False),
        ),
    ]
