# Generated by Django 4.2.7 on 2023-12-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bowlpool_app", "0003_remove_bowlgame_cfp_playoff_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bowlmatchup",
            name="away_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_team",
                to="bowlpool_app.team",
            ),
        ),
        migrations.AlterField(
            model_name="bowlmatchup",
            name="home_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_team",
                to="bowlpool_app.team",
            ),
        ),
    ]
