# Generated by Django 4.2.7 on 2023-12-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bowlpool_app", "0004_alter_bowlmatchup_away_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bowlmatchup",
            name="point_spread_extra_half",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bowlmatchup",
            name="home_team_point_spread",
            field=models.IntegerField(
                blank=True,
                help_text="Home team's point spread - negative means the home team is favored, positive means the away team is favored",
                null=True,
            ),
        ),
    ]
